# Generated by Django 2.0.3 on 2019-11-28 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(blank=True, choices=[('REALLY GOOD', 5), ('GOOD', 4), ('NOT REALLY GOOD', 3), ('BAD', 2), ('REALLY BAD', 1)], null=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Songs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
